{
  "artifacts": [
    {
      "name": "SweetPotato",
      "platform": "windows",
      "category": "bin",
      "filename": "SweetPotato.exe",
      "version": "git-288ceb4-x64",
      "source_type": "built",
      "source_ref": "https://github.com/CCob/SweetPotato",
      "sha256": "322e2926304a1367781c33886c6d032f139891fa06be69d16bac8db77f823096",
      "release_asset_name": "windows--bin--SweetPotato.exe",
      "active": true
    }
  ]
}
